### ISSUE TITLE
syntax errors in mumlib.cpp, transport.cpp and CryptState.cpp

### ISSUE THREAD

**Issue by trillhause** [slomkowski/mumlib#8]
I cloned your library, tried to run it in visual studios and got a lot of syntax errors in mumlib.cpp, transport.cpp and CryptState.cpp. Some errors occur because 'and' is used instead of '&&'. Was this on purpose?? I thought this library was for C++, if so, why do you have 'and', 'not' and 'or' in your code instead or '&&', '||' and '!'

There are also a tons of other syntax errors beside logical operators. There are missing brackets, semicolons and many more. Is this library complete ??

![pasted image at 2016_01_21 01_08 pm](https://cloud.githubusercontent.com/assets/7663087/12489821/37ebb878-c040-11e5-8d69-10815ad70339.png)

**Comment by slomkowski** [comment]
`and`, `or`, `not` are valid C++ operators: http://stackoverflow.com/a/1433352/5419223
I use them since they are more readable than symbolic ones.

The library is more or less completed. It compiles successfully with GCC and Clang under Linux. Your problems may come from some library macro which is not available in your environment. Make sure you're using C++11 as well.

Compilation under Windows, although possible, may be problematic because I use _pkg-config_ package in CMake script, which is Linux-specific. You have to include the libraries manually.

**Comment by ysblokje** [comment]
Also you might want to increase the needed cmake version to something like 3.1.0 and add set(CMAKE_CXX_STANDARD 11) that helps with some compilers. It wil set some extra switches to get it to be as near the C++11 standard as possible. 
The VS compilers are not known for their standards support. But 2013 and up should support c++11.

**Comment by slomkowski** [comment]
@millingab: did you succeed with the compilation? Any new issues?

**Comment by trillhause** [comment]
@slomkowski I tried for a few days, but it was out of my scope of knowledge to make it work for windows. My final goal is to use mumble in Unreal Engine. I have decided to connect to mumble in a Unreal Project. I will close this issue anyways.
